cargo-features = ["per-package-target"]

[package]
name = "examples-runner"
version = "0.1.0"
edition = "2024"
autobins = false
forced-target = "wasm32-unknown-unknown"

[lib]
name = "examples_runner"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
postcard = { version = "1.0", features = ["use-std"] }
plugin-sdk = { path = "../plugin-sdk" }